#!/bin/bash
#SBATCH --job-name=addgroup_MarkDup_sort_Mappeds         # Job name
#SBATCH --partition=highmem_p             # Partition (queue) name
#SBATCH --ntasks=1                    # Run on a single CPU
#SBATCH --mem=400gb                     # Job memory request
#SBATCH --time=150:00:00               # Time limit hrs:min:sec
#SBATCH --output=log_addgr_dup_mapped.%j.out    # Standard output log
#SBATCH --error=log_addgr_dup_mapped.%j.err     # Standard error log

#SBATCH --mail-type=END,FAIL          # Mail events (NONE, BEGIN, END, FAIL, ALL)
#SBATCH --mail-user=gb92068@uga.edu  # Where to send mail

cd $SLURM_SUBMIT_DIR

index_tray='/scratch/gb92068/muscadine_snp_calling/muscat_of_alexandra_snp_calling/trayIndex/'
fastq='/scratch/gb92068/muscadine_snp_calling/muscat_of_alexandra_snp_calling/paired_fastq/'
sam='/scratch/gb92068/muscadine_snp_calling/muscat_of_alexandra_snp_calling/output/samDir/'

ml picard/2.16.0-Java-1.8.0_144
ml SAMtools/1.10-iccifort-2019.5.281



##Add or replace read group
java -jar $EBROOTPICARD/picard.jar AddOrReplaceReadGroups  I=$sam/SRR5891985_paired.bam O=$sam/SRR5891985_a.bam RGID=Muscat RGLB=Muscat RGPL=ILLUMINA RGPU=Muscat RGSM=Muscat


##Filtering unmapped reads
time samtools view -bhF 4 $sam/SRR5891985_a.bam  > $sam/SRR5891985_am.bam

## Markduplicates, sort and index
gatk --java-options "-Xmx64g" MarkDuplicatesSpark -I $sam/SRR5891985_am.bam  -M $sam/dedup_metrics.txt -O $sam/SRR5891985_amsd.bam


##Collect Alignment & Insert Size Metrics
java -jar $EBROOTPICARD/picard.jar CollectAlignmentSummaryMetrics R=$index_tray/VITMroTrayshed_v2_0_ChrRenamed.fasta I=$sam/SRR5891985_amsd.bam  O=$sam/alignment_metrics.txt
java -jar $EBROOTPICARD/picard.jar CollectInsertSizeMetrics INPUT=$sam/SRR5891985_amsd.bam  OUTPUT=$sam/insert_metrics.txt HISTOGRAM_FILE=$sam/insert_size_histogram.pdf

time samtools depth -a $sam/SRR5891985_amsd.bam > $sam/depth_out.txt


##Run haplotype caller
ml GATK/4.1.6.0-GCCcore-8.3.0-Java-1.8
gatk --java-options "-Xmx64g" HaplotypeCaller -R $index_tray/VITMroTrayshed_v2_0_ChrRenamed.fasta -I $sam/SRR5891985_amsd.bam -O $sam/raw_variants.vcf


##Select variants
gatk --java-options "-Xmx64g" SelectVariants -R $index_tray/VITMroTrayshed_v2_0_ChrRenamed.fasta -V $sam/raw_variants.vcf -selectType SNP -o $sam/raw_snps.vcf
gatk --java-options "-Xmx64g" SelectVariants -R $index_tray/VITMroTrayshed_v2_0_ChrRenamed.fasta -V $sam/raw_variants.vcf -selectType INDEL -o $sam/raw_indel.vcf
